expNumber: "1"
envName: "PandaReach-v2"             
total_timesteps: 20000
mode: True                           
algorithm: "DDPG"                    
policy: "MultiInputPolicy"  
learning_starts: 1500         
render: False                        
gamma: 0.95                          
batch_size: 2048
buffer_size: 100000
rb_kwargs : {'online_sampling' : True,
             'goal_selection_strategy' : 'future',
             'n_sampled_goal' : 4}

policy_kwargs : {'net_arch' : [64, 64], 
                 'n_critics' : 2}
